document.write("<h1>Rules for naming JS Variables</h1>");
document.write("<br>");
document.write("<br>");
document.write("Variable names can only contain,numbers,$and_.For example: $my_1stVariable");
document.write("<br>");
document.write("Variables must begin with a letter, $ or _.For example $name, _name or name");
document.write("<br>");
document.write("Variable names are case sensitive");
document.write("<br>");
document.write("Variable names should not be JS keywords");